apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pb0a1rjya-java-quarkus
  janus-idp.io/tekton: pb0a1rjya-java-quarkus
  backstage.io/kubernetes-id: pb0a1rjya-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pb0a1rjya-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
